# Non-standard images are only available from fedora-testing
FROM quay.io/fedora/fedora-bootc:42
# automatically populated with --arch
ARG TARGETARCH
LABEL arch=$TARGETARCH

RUN systemctl enable sshd.service

# Reverse Proxy
RUN dnf install -y 'dnf5-command(copr)'
RUN dnf copr enable @caddy/caddy
RUN dnf install -y caddy

# Enable updating system Caddyfile/Caddyfile.d through Container Image updates
RUN mv /etc/caddy/Caddyfile /usr/lib/systemd/system/Caddyfile
RUN mv /etc/caddy/Caddyfile.d /usr/lib/systemd/system/Caddyfile.d
RUN echo 'import /usr/lib/systemd/system/Caddyfile' > /etc/caddy/Caddyfile
COPY Caddyfile /usr/lib/systemd/system/Caddyfile

RUN systemctl enable caddy.service

# MTA
WORKDIR /tmp
RUN curl -o stalwart.tar.gz -L https://github.com/stalwartlabs/stalwart/releases/download/v0.14.1/stalwart-x86_64-unknown-linux-gnu.tar.gz && \
    printf '%s  stalwart.tar.gz\n' "873ba2a29eef92e1c90d150cf0869e7b8f8f75bcb469e049ff08ef5de0dabb17" | sha256sum -c
RUN tar xvf stalwart.tar.gz
RUN mv stalwart /usr/bin/stalwart && chmod +x /usr/bin/stalwart
RUN mkdir /etc/stalwart
COPY stalwart.toml /etc/stalwart/config.toml
COPY stalwart.service /usr/lib/systemd/system/stalwart.service
COPY stalwart.caddyfile /usr/lib/systemd/system/Caddyfile.d/stalwart.caddyfile
RUN systemctl enable stalwart.service

