FROM ghcr.io/intcube-io/stalwart:latest
ARG TARGETARCH
LABEL arch=$TARGETARCH

RUN mkdir -p /etc/gophish
COPY config.json /etc/gophish/config.json
COPY gophish.container /usr/share/containers/systemd/gophish.container
COPY gophish.caddyfile /usr/lib/systemd/system/Caddyfile.d/gophish.caddyfile
