name: Build bootc-capable OCI images
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:  
      # Step 1: Checkout the code  
      - name: Checkout Repository  
        uses: actions/checkout@v4
      
      # Step 2: Build the container image(s)
      - name: Build Container Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: stalwart
          tags: latest ${{ github.sha }}
          build-args: |
            COMMIT=${{ github.sha }}
          containerfiles: |
            ./stalwart/Containerfile
          context: |
            ./stalwart

      # Step 3: Push the image to GHCR  
      - name: Push Image to GHCR
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

